// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cast_channel.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cast_channel.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace extensions {
namespace api {
namespace cast_channel {

void protobuf_ShutdownFile_cast_5fchannel_2eproto() {
  delete CastMessage::default_instance_;
  delete AuthChallenge::default_instance_;
  delete AuthResponse::default_instance_;
  delete AuthError::default_instance_;
  delete DeviceAuthMessage::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_cast_5fchannel_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_cast_5fchannel_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  CastMessage::default_instance_ = new CastMessage();
  AuthChallenge::default_instance_ = new AuthChallenge();
  AuthResponse::default_instance_ = new AuthResponse();
  AuthError::default_instance_ = new AuthError();
  DeviceAuthMessage::default_instance_ = new DeviceAuthMessage();
  CastMessage::default_instance_->InitAsDefaultInstance();
  AuthChallenge::default_instance_->InitAsDefaultInstance();
  AuthResponse::default_instance_->InitAsDefaultInstance();
  AuthError::default_instance_->InitAsDefaultInstance();
  DeviceAuthMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cast_5fchannel_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_cast_5fchannel_2eproto_once_);
void protobuf_AddDesc_cast_5fchannel_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_cast_5fchannel_2eproto_once_,
                 &protobuf_AddDesc_cast_5fchannel_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cast_5fchannel_2eproto {
  StaticDescriptorInitializer_cast_5fchannel_2eproto() {
    protobuf_AddDesc_cast_5fchannel_2eproto();
  }
} static_descriptor_initializer_cast_5fchannel_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

bool CastMessage_ProtocolVersion_IsValid(int value) {
  switch(value) {
    case 0:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const CastMessage_ProtocolVersion CastMessage::CASTV2_1_0;
const CastMessage_ProtocolVersion CastMessage::ProtocolVersion_MIN;
const CastMessage_ProtocolVersion CastMessage::ProtocolVersion_MAX;
const int CastMessage::ProtocolVersion_ARRAYSIZE;
#endif  // _MSC_VER
bool CastMessage_PayloadType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const CastMessage_PayloadType CastMessage::STRING;
const CastMessage_PayloadType CastMessage::BINARY;
const CastMessage_PayloadType CastMessage::PayloadType_MIN;
const CastMessage_PayloadType CastMessage::PayloadType_MAX;
const int CastMessage::PayloadType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int CastMessage::kProtocolVersionFieldNumber;
const int CastMessage::kSourceIdFieldNumber;
const int CastMessage::kDestinationIdFieldNumber;
const int CastMessage::kNamespaceFieldNumber;
const int CastMessage::kPayloadTypeFieldNumber;
const int CastMessage::kPayloadUtf8FieldNumber;
const int CastMessage::kPayloadBinaryFieldNumber;
#endif  // !_MSC_VER

CastMessage::CastMessage()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:extensions.api.cast_channel.CastMessage)
}

void CastMessage::InitAsDefaultInstance() {
}

CastMessage::CastMessage(const CastMessage& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:extensions.api.cast_channel.CastMessage)
}

void CastMessage::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  protocol_version_ = 0;
  source_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destination_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  namespace__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payload_type_ = 0;
  payload_utf8_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payload_binary_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CastMessage::~CastMessage() {
  // @@protoc_insertion_point(destructor:extensions.api.cast_channel.CastMessage)
  SharedDtor();
}

void CastMessage::SharedDtor() {
  source_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destination_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  namespace__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payload_utf8_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payload_binary_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void CastMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const CastMessage& CastMessage::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_cast_5fchannel_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_cast_5fchannel_2eproto();
#endif
  return *default_instance_;
}

CastMessage* CastMessage::default_instance_ = NULL;

CastMessage* CastMessage::New(::google::protobuf::Arena* arena) const {
  CastMessage* n = new CastMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CastMessage::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<CastMessage*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 127u) {
    ZR_(protocol_version_, payload_type_);
    if (has_source_id()) {
      source_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_destination_id()) {
      destination_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_namespace_()) {
      namespace__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_payload_utf8()) {
      payload_utf8_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_payload_binary()) {
      payload_binary_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool CastMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:extensions.api.cast_channel.CastMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .extensions.api.cast_channel.CastMessage.ProtocolVersion protocol_version = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::extensions::api::cast_channel::CastMessage_ProtocolVersion_IsValid(value)) {
            set_protocol_version(static_cast< ::extensions::api::cast_channel::CastMessage_ProtocolVersion >(value));
          } else {
            unknown_fields_stream.WriteVarint32(tag);
            unknown_fields_stream.WriteVarint32(value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_source_id;
        break;
      }

      // required string source_id = 2;
      case 2: {
        if (tag == 18) {
         parse_source_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_source_id()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_destination_id;
        break;
      }

      // required string destination_id = 3;
      case 3: {
        if (tag == 26) {
         parse_destination_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_destination_id()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_namespace;
        break;
      }

      // required string namespace = 4;
      case 4: {
        if (tag == 34) {
         parse_namespace:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_namespace_()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_payload_type;
        break;
      }

      // required .extensions.api.cast_channel.CastMessage.PayloadType payload_type = 5;
      case 5: {
        if (tag == 40) {
         parse_payload_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::extensions::api::cast_channel::CastMessage_PayloadType_IsValid(value)) {
            set_payload_type(static_cast< ::extensions::api::cast_channel::CastMessage_PayloadType >(value));
          } else {
            unknown_fields_stream.WriteVarint32(tag);
            unknown_fields_stream.WriteVarint32(value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_payload_utf8;
        break;
      }

      // optional string payload_utf8 = 6;
      case 6: {
        if (tag == 50) {
         parse_payload_utf8:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_payload_utf8()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_payload_binary;
        break;
      }

      // optional bytes payload_binary = 7;
      case 7: {
        if (tag == 58) {
         parse_payload_binary:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_payload_binary()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:extensions.api.cast_channel.CastMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:extensions.api.cast_channel.CastMessage)
  return false;
#undef DO_
}

void CastMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:extensions.api.cast_channel.CastMessage)
  // required .extensions.api.cast_channel.CastMessage.ProtocolVersion protocol_version = 1;
  if (has_protocol_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->protocol_version(), output);
  }

  // required string source_id = 2;
  if (has_source_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->source_id(), output);
  }

  // required string destination_id = 3;
  if (has_destination_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->destination_id(), output);
  }

  // required string namespace = 4;
  if (has_namespace_()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->namespace_(), output);
  }

  // required .extensions.api.cast_channel.CastMessage.PayloadType payload_type = 5;
  if (has_payload_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->payload_type(), output);
  }

  // optional string payload_utf8 = 6;
  if (has_payload_utf8()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->payload_utf8(), output);
  }

  // optional bytes payload_binary = 7;
  if (has_payload_binary()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      7, this->payload_binary(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:extensions.api.cast_channel.CastMessage)
}

int CastMessage::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_protocol_version()) {
    // required .extensions.api.cast_channel.CastMessage.ProtocolVersion protocol_version = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->protocol_version());
  }

  if (has_source_id()) {
    // required string source_id = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->source_id());
  }

  if (has_destination_id()) {
    // required string destination_id = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->destination_id());
  }

  if (has_namespace_()) {
    // required string namespace = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->namespace_());
  }

  if (has_payload_type()) {
    // required .extensions.api.cast_channel.CastMessage.PayloadType payload_type = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->payload_type());
  }

  return total_size;
}
int CastMessage::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000001f) ^ 0x0000001f) == 0) {  // All required fields are present.
    // required .extensions.api.cast_channel.CastMessage.ProtocolVersion protocol_version = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->protocol_version());

    // required string source_id = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->source_id());

    // required string destination_id = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->destination_id());

    // required string namespace = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->namespace_());

    // required .extensions.api.cast_channel.CastMessage.PayloadType payload_type = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->payload_type());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_has_bits_[5 / 32] & 96) {
    // optional string payload_utf8 = 6;
    if (has_payload_utf8()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->payload_utf8());
    }

    // optional bytes payload_binary = 7;
    if (has_payload_binary()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->payload_binary());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CastMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const CastMessage*>(&from));
}

void CastMessage::MergeFrom(const CastMessage& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_protocol_version()) {
      set_protocol_version(from.protocol_version());
    }
    if (from.has_source_id()) {
      set_has_source_id();
      source_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.source_id_);
    }
    if (from.has_destination_id()) {
      set_has_destination_id();
      destination_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.destination_id_);
    }
    if (from.has_namespace_()) {
      set_has_namespace_();
      namespace__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.namespace__);
    }
    if (from.has_payload_type()) {
      set_payload_type(from.payload_type());
    }
    if (from.has_payload_utf8()) {
      set_has_payload_utf8();
      payload_utf8_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.payload_utf8_);
    }
    if (from.has_payload_binary()) {
      set_has_payload_binary();
      payload_binary_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.payload_binary_);
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void CastMessage::CopyFrom(const CastMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CastMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;

  return true;
}

void CastMessage::Swap(CastMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CastMessage::InternalSwap(CastMessage* other) {
  std::swap(protocol_version_, other->protocol_version_);
  source_id_.Swap(&other->source_id_);
  destination_id_.Swap(&other->destination_id_);
  namespace__.Swap(&other->namespace__);
  std::swap(payload_type_, other->payload_type_);
  payload_utf8_.Swap(&other->payload_utf8_);
  payload_binary_.Swap(&other->payload_binary_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.swap(other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string CastMessage::GetTypeName() const {
  return "extensions.api.cast_channel.CastMessage";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CastMessage

// required .extensions.api.cast_channel.CastMessage.ProtocolVersion protocol_version = 1;
bool CastMessage::has_protocol_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void CastMessage::set_has_protocol_version() {
  _has_bits_[0] |= 0x00000001u;
}
void CastMessage::clear_has_protocol_version() {
  _has_bits_[0] &= ~0x00000001u;
}
void CastMessage::clear_protocol_version() {
  protocol_version_ = 0;
  clear_has_protocol_version();
}
 ::extensions::api::cast_channel::CastMessage_ProtocolVersion CastMessage::protocol_version() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.CastMessage.protocol_version)
  return static_cast< ::extensions::api::cast_channel::CastMessage_ProtocolVersion >(protocol_version_);
}
 void CastMessage::set_protocol_version(::extensions::api::cast_channel::CastMessage_ProtocolVersion value) {
  assert(::extensions::api::cast_channel::CastMessage_ProtocolVersion_IsValid(value));
  set_has_protocol_version();
  protocol_version_ = value;
  // @@protoc_insertion_point(field_set:extensions.api.cast_channel.CastMessage.protocol_version)
}

// required string source_id = 2;
bool CastMessage::has_source_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void CastMessage::set_has_source_id() {
  _has_bits_[0] |= 0x00000002u;
}
void CastMessage::clear_has_source_id() {
  _has_bits_[0] &= ~0x00000002u;
}
void CastMessage::clear_source_id() {
  source_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_source_id();
}
 const ::std::string& CastMessage::source_id() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.CastMessage.source_id)
  return source_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CastMessage::set_source_id(const ::std::string& value) {
  set_has_source_id();
  source_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:extensions.api.cast_channel.CastMessage.source_id)
}
 void CastMessage::set_source_id(const char* value) {
  set_has_source_id();
  source_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:extensions.api.cast_channel.CastMessage.source_id)
}
 void CastMessage::set_source_id(const char* value, size_t size) {
  set_has_source_id();
  source_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:extensions.api.cast_channel.CastMessage.source_id)
}
 ::std::string* CastMessage::mutable_source_id() {
  set_has_source_id();
  // @@protoc_insertion_point(field_mutable:extensions.api.cast_channel.CastMessage.source_id)
  return source_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CastMessage::release_source_id() {
  clear_has_source_id();
  return source_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CastMessage::set_allocated_source_id(::std::string* source_id) {
  if (source_id != NULL) {
    set_has_source_id();
  } else {
    clear_has_source_id();
  }
  source_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source_id);
  // @@protoc_insertion_point(field_set_allocated:extensions.api.cast_channel.CastMessage.source_id)
}

// required string destination_id = 3;
bool CastMessage::has_destination_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void CastMessage::set_has_destination_id() {
  _has_bits_[0] |= 0x00000004u;
}
void CastMessage::clear_has_destination_id() {
  _has_bits_[0] &= ~0x00000004u;
}
void CastMessage::clear_destination_id() {
  destination_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_destination_id();
}
 const ::std::string& CastMessage::destination_id() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.CastMessage.destination_id)
  return destination_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CastMessage::set_destination_id(const ::std::string& value) {
  set_has_destination_id();
  destination_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:extensions.api.cast_channel.CastMessage.destination_id)
}
 void CastMessage::set_destination_id(const char* value) {
  set_has_destination_id();
  destination_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:extensions.api.cast_channel.CastMessage.destination_id)
}
 void CastMessage::set_destination_id(const char* value, size_t size) {
  set_has_destination_id();
  destination_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:extensions.api.cast_channel.CastMessage.destination_id)
}
 ::std::string* CastMessage::mutable_destination_id() {
  set_has_destination_id();
  // @@protoc_insertion_point(field_mutable:extensions.api.cast_channel.CastMessage.destination_id)
  return destination_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CastMessage::release_destination_id() {
  clear_has_destination_id();
  return destination_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CastMessage::set_allocated_destination_id(::std::string* destination_id) {
  if (destination_id != NULL) {
    set_has_destination_id();
  } else {
    clear_has_destination_id();
  }
  destination_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), destination_id);
  // @@protoc_insertion_point(field_set_allocated:extensions.api.cast_channel.CastMessage.destination_id)
}

// required string namespace = 4;
bool CastMessage::has_namespace_() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void CastMessage::set_has_namespace_() {
  _has_bits_[0] |= 0x00000008u;
}
void CastMessage::clear_has_namespace_() {
  _has_bits_[0] &= ~0x00000008u;
}
void CastMessage::clear_namespace_() {
  namespace__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_namespace_();
}
 const ::std::string& CastMessage::namespace_() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.CastMessage.namespace)
  return namespace__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CastMessage::set_namespace_(const ::std::string& value) {
  set_has_namespace_();
  namespace__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:extensions.api.cast_channel.CastMessage.namespace)
}
 void CastMessage::set_namespace_(const char* value) {
  set_has_namespace_();
  namespace__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:extensions.api.cast_channel.CastMessage.namespace)
}
 void CastMessage::set_namespace_(const char* value, size_t size) {
  set_has_namespace_();
  namespace__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:extensions.api.cast_channel.CastMessage.namespace)
}
 ::std::string* CastMessage::mutable_namespace_() {
  set_has_namespace_();
  // @@protoc_insertion_point(field_mutable:extensions.api.cast_channel.CastMessage.namespace)
  return namespace__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CastMessage::release_namespace_() {
  clear_has_namespace_();
  return namespace__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CastMessage::set_allocated_namespace_(::std::string* namespace_) {
  if (namespace_ != NULL) {
    set_has_namespace_();
  } else {
    clear_has_namespace_();
  }
  namespace__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), namespace_);
  // @@protoc_insertion_point(field_set_allocated:extensions.api.cast_channel.CastMessage.namespace)
}

// required .extensions.api.cast_channel.CastMessage.PayloadType payload_type = 5;
bool CastMessage::has_payload_type() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void CastMessage::set_has_payload_type() {
  _has_bits_[0] |= 0x00000010u;
}
void CastMessage::clear_has_payload_type() {
  _has_bits_[0] &= ~0x00000010u;
}
void CastMessage::clear_payload_type() {
  payload_type_ = 0;
  clear_has_payload_type();
}
 ::extensions::api::cast_channel::CastMessage_PayloadType CastMessage::payload_type() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.CastMessage.payload_type)
  return static_cast< ::extensions::api::cast_channel::CastMessage_PayloadType >(payload_type_);
}
 void CastMessage::set_payload_type(::extensions::api::cast_channel::CastMessage_PayloadType value) {
  assert(::extensions::api::cast_channel::CastMessage_PayloadType_IsValid(value));
  set_has_payload_type();
  payload_type_ = value;
  // @@protoc_insertion_point(field_set:extensions.api.cast_channel.CastMessage.payload_type)
}

// optional string payload_utf8 = 6;
bool CastMessage::has_payload_utf8() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void CastMessage::set_has_payload_utf8() {
  _has_bits_[0] |= 0x00000020u;
}
void CastMessage::clear_has_payload_utf8() {
  _has_bits_[0] &= ~0x00000020u;
}
void CastMessage::clear_payload_utf8() {
  payload_utf8_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_payload_utf8();
}
 const ::std::string& CastMessage::payload_utf8() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.CastMessage.payload_utf8)
  return payload_utf8_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CastMessage::set_payload_utf8(const ::std::string& value) {
  set_has_payload_utf8();
  payload_utf8_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:extensions.api.cast_channel.CastMessage.payload_utf8)
}
 void CastMessage::set_payload_utf8(const char* value) {
  set_has_payload_utf8();
  payload_utf8_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:extensions.api.cast_channel.CastMessage.payload_utf8)
}
 void CastMessage::set_payload_utf8(const char* value, size_t size) {
  set_has_payload_utf8();
  payload_utf8_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:extensions.api.cast_channel.CastMessage.payload_utf8)
}
 ::std::string* CastMessage::mutable_payload_utf8() {
  set_has_payload_utf8();
  // @@protoc_insertion_point(field_mutable:extensions.api.cast_channel.CastMessage.payload_utf8)
  return payload_utf8_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CastMessage::release_payload_utf8() {
  clear_has_payload_utf8();
  return payload_utf8_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CastMessage::set_allocated_payload_utf8(::std::string* payload_utf8) {
  if (payload_utf8 != NULL) {
    set_has_payload_utf8();
  } else {
    clear_has_payload_utf8();
  }
  payload_utf8_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload_utf8);
  // @@protoc_insertion_point(field_set_allocated:extensions.api.cast_channel.CastMessage.payload_utf8)
}

// optional bytes payload_binary = 7;
bool CastMessage::has_payload_binary() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void CastMessage::set_has_payload_binary() {
  _has_bits_[0] |= 0x00000040u;
}
void CastMessage::clear_has_payload_binary() {
  _has_bits_[0] &= ~0x00000040u;
}
void CastMessage::clear_payload_binary() {
  payload_binary_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_payload_binary();
}
 const ::std::string& CastMessage::payload_binary() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.CastMessage.payload_binary)
  return payload_binary_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CastMessage::set_payload_binary(const ::std::string& value) {
  set_has_payload_binary();
  payload_binary_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:extensions.api.cast_channel.CastMessage.payload_binary)
}
 void CastMessage::set_payload_binary(const char* value) {
  set_has_payload_binary();
  payload_binary_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:extensions.api.cast_channel.CastMessage.payload_binary)
}
 void CastMessage::set_payload_binary(const void* value, size_t size) {
  set_has_payload_binary();
  payload_binary_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:extensions.api.cast_channel.CastMessage.payload_binary)
}
 ::std::string* CastMessage::mutable_payload_binary() {
  set_has_payload_binary();
  // @@protoc_insertion_point(field_mutable:extensions.api.cast_channel.CastMessage.payload_binary)
  return payload_binary_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CastMessage::release_payload_binary() {
  clear_has_payload_binary();
  return payload_binary_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CastMessage::set_allocated_payload_binary(::std::string* payload_binary) {
  if (payload_binary != NULL) {
    set_has_payload_binary();
  } else {
    clear_has_payload_binary();
  }
  payload_binary_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload_binary);
  // @@protoc_insertion_point(field_set_allocated:extensions.api.cast_channel.CastMessage.payload_binary)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

AuthChallenge::AuthChallenge()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:extensions.api.cast_channel.AuthChallenge)
}

void AuthChallenge::InitAsDefaultInstance() {
}

AuthChallenge::AuthChallenge(const AuthChallenge& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:extensions.api.cast_channel.AuthChallenge)
}

void AuthChallenge::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AuthChallenge::~AuthChallenge() {
  // @@protoc_insertion_point(destructor:extensions.api.cast_channel.AuthChallenge)
  SharedDtor();
}

void AuthChallenge::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void AuthChallenge::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const AuthChallenge& AuthChallenge::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_cast_5fchannel_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_cast_5fchannel_2eproto();
#endif
  return *default_instance_;
}

AuthChallenge* AuthChallenge::default_instance_ = NULL;

AuthChallenge* AuthChallenge::New(::google::protobuf::Arena* arena) const {
  AuthChallenge* n = new AuthChallenge;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AuthChallenge::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool AuthChallenge::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:extensions.api.cast_channel.AuthChallenge)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(
        input, tag, &unknown_fields_stream));
  }
success:
  // @@protoc_insertion_point(parse_success:extensions.api.cast_channel.AuthChallenge)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:extensions.api.cast_channel.AuthChallenge)
  return false;
#undef DO_
}

void AuthChallenge::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:extensions.api.cast_channel.AuthChallenge)
  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:extensions.api.cast_channel.AuthChallenge)
}

int AuthChallenge::ByteSize() const {
  int total_size = 0;

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AuthChallenge::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const AuthChallenge*>(&from));
}

void AuthChallenge::MergeFrom(const AuthChallenge& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  mutable_unknown_fields()->append(from.unknown_fields());
}

void AuthChallenge::CopyFrom(const AuthChallenge& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthChallenge::IsInitialized() const {

  return true;
}

void AuthChallenge::Swap(AuthChallenge* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AuthChallenge::InternalSwap(AuthChallenge* other) {
  _unknown_fields_.swap(other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string AuthChallenge::GetTypeName() const {
  return "extensions.api.cast_channel.AuthChallenge";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AuthChallenge

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int AuthResponse::kSignatureFieldNumber;
const int AuthResponse::kClientAuthCertificateFieldNumber;
#endif  // !_MSC_VER

AuthResponse::AuthResponse()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:extensions.api.cast_channel.AuthResponse)
}

void AuthResponse::InitAsDefaultInstance() {
}

AuthResponse::AuthResponse(const AuthResponse& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:extensions.api.cast_channel.AuthResponse)
}

void AuthResponse::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  signature_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  client_auth_certificate_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AuthResponse::~AuthResponse() {
  // @@protoc_insertion_point(destructor:extensions.api.cast_channel.AuthResponse)
  SharedDtor();
}

void AuthResponse::SharedDtor() {
  signature_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  client_auth_certificate_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void AuthResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const AuthResponse& AuthResponse::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_cast_5fchannel_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_cast_5fchannel_2eproto();
#endif
  return *default_instance_;
}

AuthResponse* AuthResponse::default_instance_ = NULL;

AuthResponse* AuthResponse::New(::google::protobuf::Arena* arena) const {
  AuthResponse* n = new AuthResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AuthResponse::Clear() {
  if (_has_bits_[0 / 32] & 3u) {
    if (has_signature()) {
      signature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_client_auth_certificate()) {
      client_auth_certificate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool AuthResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:extensions.api.cast_channel.AuthResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes signature = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_signature()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_client_auth_certificate;
        break;
      }

      // required bytes client_auth_certificate = 2;
      case 2: {
        if (tag == 18) {
         parse_client_auth_certificate:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_client_auth_certificate()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:extensions.api.cast_channel.AuthResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:extensions.api.cast_channel.AuthResponse)
  return false;
#undef DO_
}

void AuthResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:extensions.api.cast_channel.AuthResponse)
  // required bytes signature = 1;
  if (has_signature()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->signature(), output);
  }

  // required bytes client_auth_certificate = 2;
  if (has_client_auth_certificate()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->client_auth_certificate(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:extensions.api.cast_channel.AuthResponse)
}

int AuthResponse::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_signature()) {
    // required bytes signature = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->signature());
  }

  if (has_client_auth_certificate()) {
    // required bytes client_auth_certificate = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->client_auth_certificate());
  }

  return total_size;
}
int AuthResponse::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required bytes signature = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->signature());

    // required bytes client_auth_certificate = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->client_auth_certificate());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AuthResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const AuthResponse*>(&from));
}

void AuthResponse::MergeFrom(const AuthResponse& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_signature()) {
      set_has_signature();
      signature_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.signature_);
    }
    if (from.has_client_auth_certificate()) {
      set_has_client_auth_certificate();
      client_auth_certificate_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.client_auth_certificate_);
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void AuthResponse::CopyFrom(const AuthResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void AuthResponse::Swap(AuthResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AuthResponse::InternalSwap(AuthResponse* other) {
  signature_.Swap(&other->signature_);
  client_auth_certificate_.Swap(&other->client_auth_certificate_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.swap(other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string AuthResponse::GetTypeName() const {
  return "extensions.api.cast_channel.AuthResponse";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AuthResponse

// required bytes signature = 1;
bool AuthResponse::has_signature() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void AuthResponse::set_has_signature() {
  _has_bits_[0] |= 0x00000001u;
}
void AuthResponse::clear_has_signature() {
  _has_bits_[0] &= ~0x00000001u;
}
void AuthResponse::clear_signature() {
  signature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_signature();
}
 const ::std::string& AuthResponse::signature() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.AuthResponse.signature)
  return signature_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AuthResponse::set_signature(const ::std::string& value) {
  set_has_signature();
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:extensions.api.cast_channel.AuthResponse.signature)
}
 void AuthResponse::set_signature(const char* value) {
  set_has_signature();
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:extensions.api.cast_channel.AuthResponse.signature)
}
 void AuthResponse::set_signature(const void* value, size_t size) {
  set_has_signature();
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:extensions.api.cast_channel.AuthResponse.signature)
}
 ::std::string* AuthResponse::mutable_signature() {
  set_has_signature();
  // @@protoc_insertion_point(field_mutable:extensions.api.cast_channel.AuthResponse.signature)
  return signature_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* AuthResponse::release_signature() {
  clear_has_signature();
  return signature_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AuthResponse::set_allocated_signature(::std::string* signature) {
  if (signature != NULL) {
    set_has_signature();
  } else {
    clear_has_signature();
  }
  signature_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), signature);
  // @@protoc_insertion_point(field_set_allocated:extensions.api.cast_channel.AuthResponse.signature)
}

// required bytes client_auth_certificate = 2;
bool AuthResponse::has_client_auth_certificate() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void AuthResponse::set_has_client_auth_certificate() {
  _has_bits_[0] |= 0x00000002u;
}
void AuthResponse::clear_has_client_auth_certificate() {
  _has_bits_[0] &= ~0x00000002u;
}
void AuthResponse::clear_client_auth_certificate() {
  client_auth_certificate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_client_auth_certificate();
}
 const ::std::string& AuthResponse::client_auth_certificate() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.AuthResponse.client_auth_certificate)
  return client_auth_certificate_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AuthResponse::set_client_auth_certificate(const ::std::string& value) {
  set_has_client_auth_certificate();
  client_auth_certificate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:extensions.api.cast_channel.AuthResponse.client_auth_certificate)
}
 void AuthResponse::set_client_auth_certificate(const char* value) {
  set_has_client_auth_certificate();
  client_auth_certificate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:extensions.api.cast_channel.AuthResponse.client_auth_certificate)
}
 void AuthResponse::set_client_auth_certificate(const void* value, size_t size) {
  set_has_client_auth_certificate();
  client_auth_certificate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:extensions.api.cast_channel.AuthResponse.client_auth_certificate)
}
 ::std::string* AuthResponse::mutable_client_auth_certificate() {
  set_has_client_auth_certificate();
  // @@protoc_insertion_point(field_mutable:extensions.api.cast_channel.AuthResponse.client_auth_certificate)
  return client_auth_certificate_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* AuthResponse::release_client_auth_certificate() {
  clear_has_client_auth_certificate();
  return client_auth_certificate_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AuthResponse::set_allocated_client_auth_certificate(::std::string* client_auth_certificate) {
  if (client_auth_certificate != NULL) {
    set_has_client_auth_certificate();
  } else {
    clear_has_client_auth_certificate();
  }
  client_auth_certificate_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), client_auth_certificate);
  // @@protoc_insertion_point(field_set_allocated:extensions.api.cast_channel.AuthResponse.client_auth_certificate)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

bool AuthError_ErrorType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const AuthError_ErrorType AuthError::INTERNAL_ERROR;
const AuthError_ErrorType AuthError::NO_TLS;
const AuthError_ErrorType AuthError::ErrorType_MIN;
const AuthError_ErrorType AuthError::ErrorType_MAX;
const int AuthError::ErrorType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int AuthError::kErrorTypeFieldNumber;
#endif  // !_MSC_VER

AuthError::AuthError()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:extensions.api.cast_channel.AuthError)
}

void AuthError::InitAsDefaultInstance() {
}

AuthError::AuthError(const AuthError& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:extensions.api.cast_channel.AuthError)
}

void AuthError::SharedCtor() {
  _cached_size_ = 0;
  error_type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AuthError::~AuthError() {
  // @@protoc_insertion_point(destructor:extensions.api.cast_channel.AuthError)
  SharedDtor();
}

void AuthError::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void AuthError::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const AuthError& AuthError::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_cast_5fchannel_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_cast_5fchannel_2eproto();
#endif
  return *default_instance_;
}

AuthError* AuthError::default_instance_ = NULL;

AuthError* AuthError::New(::google::protobuf::Arena* arena) const {
  AuthError* n = new AuthError;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AuthError::Clear() {
  error_type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool AuthError::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:extensions.api.cast_channel.AuthError)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .extensions.api.cast_channel.AuthError.ErrorType error_type = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::extensions::api::cast_channel::AuthError_ErrorType_IsValid(value)) {
            set_error_type(static_cast< ::extensions::api::cast_channel::AuthError_ErrorType >(value));
          } else {
            unknown_fields_stream.WriteVarint32(tag);
            unknown_fields_stream.WriteVarint32(value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:extensions.api.cast_channel.AuthError)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:extensions.api.cast_channel.AuthError)
  return false;
#undef DO_
}

void AuthError::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:extensions.api.cast_channel.AuthError)
  // required .extensions.api.cast_channel.AuthError.ErrorType error_type = 1;
  if (has_error_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->error_type(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:extensions.api.cast_channel.AuthError)
}

int AuthError::ByteSize() const {
  int total_size = 0;

  // required .extensions.api.cast_channel.AuthError.ErrorType error_type = 1;
  if (has_error_type()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->error_type());
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AuthError::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const AuthError*>(&from));
}

void AuthError::MergeFrom(const AuthError& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_error_type()) {
      set_error_type(from.error_type());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void AuthError::CopyFrom(const AuthError& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthError::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void AuthError::Swap(AuthError* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AuthError::InternalSwap(AuthError* other) {
  std::swap(error_type_, other->error_type_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.swap(other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string AuthError::GetTypeName() const {
  return "extensions.api.cast_channel.AuthError";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AuthError

// required .extensions.api.cast_channel.AuthError.ErrorType error_type = 1;
bool AuthError::has_error_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void AuthError::set_has_error_type() {
  _has_bits_[0] |= 0x00000001u;
}
void AuthError::clear_has_error_type() {
  _has_bits_[0] &= ~0x00000001u;
}
void AuthError::clear_error_type() {
  error_type_ = 0;
  clear_has_error_type();
}
 ::extensions::api::cast_channel::AuthError_ErrorType AuthError::error_type() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.AuthError.error_type)
  return static_cast< ::extensions::api::cast_channel::AuthError_ErrorType >(error_type_);
}
 void AuthError::set_error_type(::extensions::api::cast_channel::AuthError_ErrorType value) {
  assert(::extensions::api::cast_channel::AuthError_ErrorType_IsValid(value));
  set_has_error_type();
  error_type_ = value;
  // @@protoc_insertion_point(field_set:extensions.api.cast_channel.AuthError.error_type)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int DeviceAuthMessage::kChallengeFieldNumber;
const int DeviceAuthMessage::kResponseFieldNumber;
const int DeviceAuthMessage::kErrorFieldNumber;
#endif  // !_MSC_VER

DeviceAuthMessage::DeviceAuthMessage()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:extensions.api.cast_channel.DeviceAuthMessage)
}

void DeviceAuthMessage::InitAsDefaultInstance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  challenge_ = const_cast< ::extensions::api::cast_channel::AuthChallenge*>(
      ::extensions::api::cast_channel::AuthChallenge::internal_default_instance());
#else
  challenge_ = const_cast< ::extensions::api::cast_channel::AuthChallenge*>(&::extensions::api::cast_channel::AuthChallenge::default_instance());
#endif
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  response_ = const_cast< ::extensions::api::cast_channel::AuthResponse*>(
      ::extensions::api::cast_channel::AuthResponse::internal_default_instance());
#else
  response_ = const_cast< ::extensions::api::cast_channel::AuthResponse*>(&::extensions::api::cast_channel::AuthResponse::default_instance());
#endif
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  error_ = const_cast< ::extensions::api::cast_channel::AuthError*>(
      ::extensions::api::cast_channel::AuthError::internal_default_instance());
#else
  error_ = const_cast< ::extensions::api::cast_channel::AuthError*>(&::extensions::api::cast_channel::AuthError::default_instance());
#endif
}

DeviceAuthMessage::DeviceAuthMessage(const DeviceAuthMessage& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:extensions.api.cast_channel.DeviceAuthMessage)
}

void DeviceAuthMessage::SharedCtor() {
  _cached_size_ = 0;
  challenge_ = NULL;
  response_ = NULL;
  error_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DeviceAuthMessage::~DeviceAuthMessage() {
  // @@protoc_insertion_point(destructor:extensions.api.cast_channel.DeviceAuthMessage)
  SharedDtor();
}

void DeviceAuthMessage::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete challenge_;
    delete response_;
    delete error_;
  }
}

void DeviceAuthMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const DeviceAuthMessage& DeviceAuthMessage::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_cast_5fchannel_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_cast_5fchannel_2eproto();
#endif
  return *default_instance_;
}

DeviceAuthMessage* DeviceAuthMessage::default_instance_ = NULL;

DeviceAuthMessage* DeviceAuthMessage::New(::google::protobuf::Arena* arena) const {
  DeviceAuthMessage* n = new DeviceAuthMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DeviceAuthMessage::Clear() {
  if (_has_bits_[0 / 32] & 7u) {
    if (has_challenge()) {
      if (challenge_ != NULL) challenge_->::extensions::api::cast_channel::AuthChallenge::Clear();
    }
    if (has_response()) {
      if (response_ != NULL) response_->::extensions::api::cast_channel::AuthResponse::Clear();
    }
    if (has_error()) {
      if (error_ != NULL) error_->::extensions::api::cast_channel::AuthError::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool DeviceAuthMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:extensions.api.cast_channel.DeviceAuthMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .extensions.api.cast_channel.AuthChallenge challenge = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_challenge()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_response;
        break;
      }

      // optional .extensions.api.cast_channel.AuthResponse response = 2;
      case 2: {
        if (tag == 18) {
         parse_response:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_response()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_error;
        break;
      }

      // optional .extensions.api.cast_channel.AuthError error = 3;
      case 3: {
        if (tag == 26) {
         parse_error:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_error()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:extensions.api.cast_channel.DeviceAuthMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:extensions.api.cast_channel.DeviceAuthMessage)
  return false;
#undef DO_
}

void DeviceAuthMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:extensions.api.cast_channel.DeviceAuthMessage)
  // optional .extensions.api.cast_channel.AuthChallenge challenge = 1;
  if (has_challenge()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, *this->challenge_, output);
  }

  // optional .extensions.api.cast_channel.AuthResponse response = 2;
  if (has_response()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, *this->response_, output);
  }

  // optional .extensions.api.cast_channel.AuthError error = 3;
  if (has_error()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, *this->error_, output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:extensions.api.cast_channel.DeviceAuthMessage)
}

int DeviceAuthMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 7) {
    // optional .extensions.api.cast_channel.AuthChallenge challenge = 1;
    if (has_challenge()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->challenge_);
    }

    // optional .extensions.api.cast_channel.AuthResponse response = 2;
    if (has_response()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->response_);
    }

    // optional .extensions.api.cast_channel.AuthError error = 3;
    if (has_error()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->error_);
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DeviceAuthMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const DeviceAuthMessage*>(&from));
}

void DeviceAuthMessage::MergeFrom(const DeviceAuthMessage& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_challenge()) {
      mutable_challenge()->::extensions::api::cast_channel::AuthChallenge::MergeFrom(from.challenge());
    }
    if (from.has_response()) {
      mutable_response()->::extensions::api::cast_channel::AuthResponse::MergeFrom(from.response());
    }
    if (from.has_error()) {
      mutable_error()->::extensions::api::cast_channel::AuthError::MergeFrom(from.error());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void DeviceAuthMessage::CopyFrom(const DeviceAuthMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeviceAuthMessage::IsInitialized() const {

  if (has_response()) {
    if (!this->response_->IsInitialized()) return false;
  }
  if (has_error()) {
    if (!this->error_->IsInitialized()) return false;
  }
  return true;
}

void DeviceAuthMessage::Swap(DeviceAuthMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DeviceAuthMessage::InternalSwap(DeviceAuthMessage* other) {
  std::swap(challenge_, other->challenge_);
  std::swap(response_, other->response_);
  std::swap(error_, other->error_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.swap(other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string DeviceAuthMessage::GetTypeName() const {
  return "extensions.api.cast_channel.DeviceAuthMessage";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DeviceAuthMessage

// optional .extensions.api.cast_channel.AuthChallenge challenge = 1;
bool DeviceAuthMessage::has_challenge() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void DeviceAuthMessage::set_has_challenge() {
  _has_bits_[0] |= 0x00000001u;
}
void DeviceAuthMessage::clear_has_challenge() {
  _has_bits_[0] &= ~0x00000001u;
}
void DeviceAuthMessage::clear_challenge() {
  if (challenge_ != NULL) challenge_->::extensions::api::cast_channel::AuthChallenge::Clear();
  clear_has_challenge();
}
 const ::extensions::api::cast_channel::AuthChallenge& DeviceAuthMessage::challenge() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.DeviceAuthMessage.challenge)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return challenge_ != NULL ? *challenge_ : *default_instance().challenge_;
#else
  return challenge_ != NULL ? *challenge_ : *default_instance_->challenge_;
#endif
}
 ::extensions::api::cast_channel::AuthChallenge* DeviceAuthMessage::mutable_challenge() {
  set_has_challenge();
  if (challenge_ == NULL) {
    challenge_ = new ::extensions::api::cast_channel::AuthChallenge;
  }
  // @@protoc_insertion_point(field_mutable:extensions.api.cast_channel.DeviceAuthMessage.challenge)
  return challenge_;
}
 ::extensions::api::cast_channel::AuthChallenge* DeviceAuthMessage::release_challenge() {
  clear_has_challenge();
  ::extensions::api::cast_channel::AuthChallenge* temp = challenge_;
  challenge_ = NULL;
  return temp;
}
 void DeviceAuthMessage::set_allocated_challenge(::extensions::api::cast_channel::AuthChallenge* challenge) {
  delete challenge_;
  challenge_ = challenge;
  if (challenge) {
    set_has_challenge();
  } else {
    clear_has_challenge();
  }
  // @@protoc_insertion_point(field_set_allocated:extensions.api.cast_channel.DeviceAuthMessage.challenge)
}

// optional .extensions.api.cast_channel.AuthResponse response = 2;
bool DeviceAuthMessage::has_response() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void DeviceAuthMessage::set_has_response() {
  _has_bits_[0] |= 0x00000002u;
}
void DeviceAuthMessage::clear_has_response() {
  _has_bits_[0] &= ~0x00000002u;
}
void DeviceAuthMessage::clear_response() {
  if (response_ != NULL) response_->::extensions::api::cast_channel::AuthResponse::Clear();
  clear_has_response();
}
 const ::extensions::api::cast_channel::AuthResponse& DeviceAuthMessage::response() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.DeviceAuthMessage.response)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return response_ != NULL ? *response_ : *default_instance().response_;
#else
  return response_ != NULL ? *response_ : *default_instance_->response_;
#endif
}
 ::extensions::api::cast_channel::AuthResponse* DeviceAuthMessage::mutable_response() {
  set_has_response();
  if (response_ == NULL) {
    response_ = new ::extensions::api::cast_channel::AuthResponse;
  }
  // @@protoc_insertion_point(field_mutable:extensions.api.cast_channel.DeviceAuthMessage.response)
  return response_;
}
 ::extensions::api::cast_channel::AuthResponse* DeviceAuthMessage::release_response() {
  clear_has_response();
  ::extensions::api::cast_channel::AuthResponse* temp = response_;
  response_ = NULL;
  return temp;
}
 void DeviceAuthMessage::set_allocated_response(::extensions::api::cast_channel::AuthResponse* response) {
  delete response_;
  response_ = response;
  if (response) {
    set_has_response();
  } else {
    clear_has_response();
  }
  // @@protoc_insertion_point(field_set_allocated:extensions.api.cast_channel.DeviceAuthMessage.response)
}

// optional .extensions.api.cast_channel.AuthError error = 3;
bool DeviceAuthMessage::has_error() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void DeviceAuthMessage::set_has_error() {
  _has_bits_[0] |= 0x00000004u;
}
void DeviceAuthMessage::clear_has_error() {
  _has_bits_[0] &= ~0x00000004u;
}
void DeviceAuthMessage::clear_error() {
  if (error_ != NULL) error_->::extensions::api::cast_channel::AuthError::Clear();
  clear_has_error();
}
 const ::extensions::api::cast_channel::AuthError& DeviceAuthMessage::error() const {
  // @@protoc_insertion_point(field_get:extensions.api.cast_channel.DeviceAuthMessage.error)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return error_ != NULL ? *error_ : *default_instance().error_;
#else
  return error_ != NULL ? *error_ : *default_instance_->error_;
#endif
}
 ::extensions::api::cast_channel::AuthError* DeviceAuthMessage::mutable_error() {
  set_has_error();
  if (error_ == NULL) {
    error_ = new ::extensions::api::cast_channel::AuthError;
  }
  // @@protoc_insertion_point(field_mutable:extensions.api.cast_channel.DeviceAuthMessage.error)
  return error_;
}
 ::extensions::api::cast_channel::AuthError* DeviceAuthMessage::release_error() {
  clear_has_error();
  ::extensions::api::cast_channel::AuthError* temp = error_;
  error_ = NULL;
  return temp;
}
 void DeviceAuthMessage::set_allocated_error(::extensions::api::cast_channel::AuthError* error) {
  delete error_;
  error_ = error;
  if (error) {
    set_has_error();
  } else {
    clear_has_error();
  }
  // @@protoc_insertion_point(field_set_allocated:extensions.api.cast_channel.DeviceAuthMessage.error)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace cast_channel
}  // namespace api
}  // namespace extensions

// @@protoc_insertion_point(global_scope)
